name: cgan
channels:
  - conda-forge
dependencies:
  - conda
  - python=3.9
  - cudnn=8.1.0
  - cudatoolkit=11.2
  - matplotlib
  - pandas
  - jupyter
  - numba
  - cfgrib
  - dask
  - seaborn
  - tqdm
  - xarray
  - properscoring
  - netcdf4
  - h5netcdf
  - cartopy
  - climlab
  - iris
  - scikit-learn
  - tensorflow=2.8.2
  - keras-preprocessing
  - black
  - pytest
  - numpy
  - xesmf
  - gitpython
  - wandb
  - timezonefinder
  - metpy

