name: cgan_stable
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cudnn=8.9.7
  - cudatoolkit=11.8
  - matplotlib
  - pandas
  - jupyter
  - numba
  - cfgrib
  - dask
  - seaborn
  - tqdm
  - xarray
  - properscoring
  - netcdf4
  - h5netcdf
  - cartopy
  - climlab
  - iris
  - scikit-learn
  - keras
  - black
  - pytest
  - numpy<2.0
  - esmf=8.6.0
  - esmpy=8.6.0
  - xesmf
  - gitpython
  - wandb
  - timezonefinder
  - metpy
  - jupytext
  pip:
    - tensorflow[and-cuda]==2.15.0
