name: cgan_new
channels:
  - conda-forge
dependencies:
  - pip
  # - python=3.
  - cudnn
  - cudatoolkit
  - matplotlib
  - pandas
  - jupyter
  - numba
  - cfgrib
  - dask
  - seaborn
  - tqdm
  - xarray
  - properscoring
  - netcdf4
  - h5netcdf
  - cartopy
  - climlab
  - iris
  - scikit-learn
  - keras-preprocessing
  - black
  - pytest
  - numpy
  - esmf=8.4.1
  - esmpy=8.4.1
  - xesmf
  - gitpython
  - wandb
  - timezonefinder
  - metpy
  - gitpython  # Duplicated entry
  - jupytext
  # pip:
  #   - tensorflow-gpu=2.8.2
